channels:
  - bioconda
  - conda-forge
dependencies:
  - python =3.6
  - snakemake-minimal >=5.24.1
  - jinja2 =2.11
  - networkx =2.5
  - matplotlib =3.3
  - graphviz =2.42
  - samtools =1.10
  - fastp =0.20.1
  - minimap2 =2.17
  - bowtie2 =2.4.1
  - cython =0.29.6 
  - biom-format =2.1.8
  - pigz =2.4
  - pip
  - pip:
    - git+https://github.com/qiyunzhu/woltka.git
