#input definitions
WORKDIR: "/klaster/scratch/kkopera/COVID/microbiome/snakemake/QC_and_FT_advanced/polish-microbiome-project/shallow-shotgun-analysis-workflow"


#referenece genome for minimap2_index
ref_hum_gen: './../../prebuilt_data/GCA_000001405.15_GRCh38_genomic.fna.gz' 
#referenece genome for bowtie2_index
ref_bac_gen: './../../prebuilt_data/rep82.fna'


# compute on N thread
THREADS: 8

##########
#FASTP
##########
fastp:
    adapter_fasta: './../../prebuilt_data/adapters.fasta' #a FASTA file to trim both read1 and read2
    q: 15 #the quality value that a base is qualified
    u: 40 #how many percents of bases are allowed to be unqualified
            #extra params for fastp
            # -y -  enable low complexity filter
            # -p -  enable overrepresented sequence analysis
    extra: '-y -p' #extra parameters

##########
#MULTIQC
##########
multiqc_extra: '' #extra parameters

##########
#MINIMAP2_INDEX
##########
minimap2_index_extra: '-a -x map-ont' #extra parameters

##########
#MINIMAP2
##########
minimap2_extra: '-a -x map-ont' #extra parameters

##########
#BOWTIE2_INDEX
##########
bowtie2_index_extra: '--large-index'

##########
#BOWTIE2
# The parameters in config_template are taken from SHOGUN
##########
bowtie2:
    np: 1 #penalty for positions where the read, reference, or both, contain an ambiguous character such as N
    mp: '1,1' #Sets the maximum (MX) and minimum (MN) mismatch penalties, both integers
    rdg: '0,1' #Sets the read gap open (<int1>) and extend (<int2>) penalties. A read gap of length N gets a penalty of <int1> + N * <int2>. Default: 5, 3.
    rfg: '0,1' #Sets the reference gap open (<int1>) and extend (<int2>) penalties. A reference gap of length N gets a penalty of <int1> + N * <int2>. Default: 5, 3"
    score_min: 'L,0,-0.02' #Sets a function governing the minimum alignment score needed for an alignment to be considered "valid" (i.e. good enough to report). 
    k: 16 #searches for at most <int> distinct, valid alignments for each read. The search terminates when it can't find more distinct valid alignments, or when it finds <int>, whichever happens first.
    #--met-file - Write bowtie2 metrics to file <path>.
    #--reorder  - Guarantees that output SAM records are printed in an order corresponding to the order of the reads in the original input file, even when -p is set greater than 1. 
    #--very-sensitive - Preset parameters. Same as: -D 20 -R 3 -N 0 -L 20 -i S,1,0.50
    #--no-hd - Suppress SAM header lines (starting with @).
    #--no-unal - Suppress SAM records for reads that failed to align.
    extra: '--met-file --reorder --very-sensitive --no-hd --no-unal'

##########
#WOLTKA_GOTU
##########
woltka_gotu_extra: ''  #extra parameters



